### ISSUE TITLE
Licensing Issue with NamedParameterStatement

### ISSUE THREAD

**Issue by skavanagh** [lightblue-platform/lightblue-rdbms#75]
At a glance much of the implementation is copied from

https://github.com/bnewport/Samples/blob/master/wxsutils/src/main/java/com/devwebsphere/jdbc/loader/NamedParameterStatement.java

which looks to have a non-permissive license
https://github.com/bnewport/Samples/blob/master/wxsutils/LICENSE
```
This sample program is provided AS IS and may be used, executed, copied and
modified without royalty payment by customer (a) for its own instruction and 
study, (b) in order to develop applications designed to run with an IBM 
WebSphere product, either for customer's own internal use or for redistribution 
by customer, as part of such an application, in customer's own products. "

5724-J34 (C) COPYRIGHT International Business Machines Corp. 2009
All Rights Reserved * Licensed Materials - Property of IBM
```
You could switch to use this one... https://github.com/colloquium/spacewalk/blob/d4bee4ec00fc89e00dd5c74a684298ebf0e2f686/java/code/src/com/redhat/rhn/common/db/NamedPreparedStatement.java
Looks like a new implementation under GPLv2

**Comment by luan-cestari** [comment]
https://github.com/lightblue-platform/lightblue-rdbms/pull/107
