### ISSUE TITLE
Wildcard projection causes NullPointerException

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-rdbms#96]
Specifying a wildcard projection like this one on an RDBMS entity

{
  "objectType":"country",
  "version":"1.0.0",
  "projection": [ 
     { 
       "field": "*", 
       "include": true, 
       "recursive": true
     }
   ],
  "query" : { "field":"iso2code","op":"=","rvalue":"US" }
}

causes a NullPointerException at https://github.com/lightblue-platform/lightblue-rdbms/blob/master/metadata/src/main/java/com/redhat/lightblue/metadata/rdbms/converter/TranslationContext.java#L136

**Comment by derek63** [comment]
The NPE also happens if you explicitly specify any field it can't find in the result

**Comment by luan-cestari** [comment]
PR to fix that:
https://github.com/lightblue-platform/lightblue-rdbms/pull/100
https://github.com/lightblue-platform/lightblue-rest/pull/83
