### ISSUE TITLE
Data is returned as elements of processed array (not as objects inside it)

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-rdbms#97]
When submitting a query like the following:
```
{
  "objectType":"country",
  "version":"1.0.0",
  "projection": [ 
    { "field" : "iso2code", "include" :  true},
  ],
  "query" : { "field":"iso2code","op":"=","rvalue":"US" }
}
```
I am receiving a response that contains the value of the projection I am asking for as an element of the processed array (and the matchCount is off it seems)
```
{
  "status" : "COMPLETE",
  "processed" : [
    "US"
  ],
  "modifiedCount" : 0,
  "matchCount" : 0
}
```
What I would expect to see is something like this, where the field I asked for is included in an object inside the processed array (with the correct match count).
```
{
  "status" : "COMPLETE",
  "processed" : [
    {
      "iso2code" : "US"
    }
  ],
  "modifiedCount" : 0,
  "matchCount" : 1
}
```

**Comment by bserdar** [comment]
RDBMSProcessor.convertProjection is the problem. It is producing JsonDoc objects containing values from the SQL queries, it is not building a document conformant to the entity metadata.

**Comment by bserdar** [comment]
There should be a mapping of fields -> values, and the Json document should be built using JsonDoc.modify calls.
